### PR TITLE
Add Express app instructions

### PR DESCRIPTION
**Pull request by sprice**
Add instructions for Express apps to README

### CODE REVIEW

**Comment by dmathieu** [comment]
Hey Shawn,

Thank you for your work here. Your index.js file is 27 lines. Does it really need an external package?
I've tried keeping all the examples in this readme simple and generic. People might not be able to use your package, or need to make changes to it.

**Comment by sprice** [comment]
If you're happier just having a route definition that's cool. I'm not sure how an express app couldn't use this, or why they would need to make a change 😄 . I'll close this and create another

**Comment by dmathieu** [comment]
Thank you.
More than needing to make a change, it's also a question of visibility around what this actually does.

And -not that you'd ever do that-, a fear for leftpad :wink:

**Comment by sprice** [comment]
haha. I feel that leftpad may have ruined the whole idea of "use many modules" for node

**Comment by dmathieu** [comment]
To be fair, I'd have said that for any language, not only node.

**Pull request closed without merging**
